class Texts(object):
    def __init__(self):
        self.APP_TITLE = "Swag Labs"
        self.LOGIN_USERNAME_HELPER = "Accepted usernames are:standard_userlocked_out_userproblem_userperformance_glitch_usererror_uservisual_user"
        self.LOGIN_PASSWORD_HELPER = "Password for all users:secret_sauce"
        self.LOGIN_BUTTON = "Login"
        self.LOCKED_OUT_USER_ERROR = "Epic sadface: Sorry, this user has been locked out."
        self.PAYMENT_INFORMATION = "Payment Information:"
        self.SHIPPING_INFORMATION = "Shipping Information:"
        self.PRICE_TOTAL = "Price Total"
        self.ITEM_TOTAL_VALUE = "Item total: {}"
        self.TAX_VALUE = "Tax: {}"
        self.ORDER_TOTAL_VALUE = "Total: {}"
        self.CANCEL = "Cancel"
        self.FINISH = "Finish"
