name: Trigger Tests

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'run identifier'
        required: false
        type: string
      test:
        description: 'What test should be executed - more details in pyproject.toml'
        default: 'all'
        required: false
        type: string
      browser:
        description: 'Select browser for testing'
        type: choice
        required: true
        default: 'chromium'
        options:
          - chromium
          - firefox
          - webkit

env:
  DOCKER_REPOSITORY: ${{ github.repository }}

jobs:
  run-e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull docker image
      run: docker pull ${{ env.DOCKER_REPOSITORY }}:latest

    - name: Create dir for results
      run: mkdir results

    - name: Running docker ${{ inputs.id }}
      id: e2e-tests
      run: |-
        docker run --rm -e BROWSER="${{ inputs.browser }}" \
         -e TEST="${{ inputs.test }}" \
         -v $(pwd)/results:/app/results vitoralm/pytest-playwright-tests:latest
        
    - name: Save artifacts
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        overwrite: true
        name: results
        path: results

